template_url/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url('relative/', views.relative, name='relative'),
    url('other/', views.other, name='other'),
]

template_url/template_url/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls'))
]

template_url/basic_app/models.py
from django.db import models

# Create your models here.

template_url/basic_app/views.py
from django.shortcuts import render

def index(request):
    context_dict = {'text':'hello world!','number':123}
    return render(request,'basic_app/index.html',context= context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url.html')

template_url/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="containers">

        {% block body_block %}
        {% endblock %}

    </div>
</body>
</html>

template_url/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to index!</h1>
    <h3>{{ text|cut:'hello' }}</h3>
    <h2>{{ number|add:"99" }}</h2>
{% endblock %}

template_url/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

    <h1>Welcome to other!</h1>
    <a href="{% url 'basic_app:relative' %}">Go to relative</a>
    
    {% endblock %}

template_url/basic_app/templates/basic_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative_url</h1>
    <a href="{% url 'basic_app:other' %}">Go to other</a>
    <a href="{% url 'admin:index' %}">Go to admin</a>
    <a href="{% url 'index' %}">Go to index</a>
</body>
</html>